<#
.SYNOPSIS
  Run the local Ollama-backed agent (via Codex CLI) on a GitHub issue or an ad-hoc task,
  on its own branch, and open a pull request for review by another agent.

.DESCRIPTION
  Reads AGENTS.md rules through Codex itself. Uses `codex exec` (non-interactive) with the
  `local` or `local-heavy` profile from ~/.codex/config.toml (see tools/codex-config.example.toml).

.EXAMPLE
  .\tools\agent-local.ps1 -Issue 12
  .\tools\agent-local.ps1 -Task "Add docstrings to tools/docx2md.py" -Profile local-heavy -NoPR
#>
[CmdletBinding()]
param(
  [int]$Issue,
  [string]$Task,
  [ValidateSet('local', 'local-heavy')]
  [string]$Profile = 'local',
  [switch]$NoPR
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
Set-Location $repo

if (-not $Issue -and -not $Task) { throw "Give -Issue <number> or -Task '<text>'." }
foreach ($tool in 'git', 'gh', 'codex') {
  if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) { throw "$tool is not on PATH." }
}

# Clean, current main.
git diff --quiet; if ($LASTEXITCODE -ne 0) { throw "Working tree has uncommitted changes. Commit or stash first." }
git checkout -q main
git pull -q --ff-only

$modelLabel = if ($Profile -eq 'local-heavy') { 'qwen3.6:35b' } else { 'qwen3.5:9b' }

if ($Issue) {
  $meta = gh issue view $Issue --json title,body,labels | ConvertFrom-Json
  $title = $meta.title
  $branch = "agent-local/issue-$Issue"
  $prompt = @"
You are the LOCAL agent for this repository (model: $modelLabel). Read AGENTS.md first and follow it, especially the "Local agent" rules.

Work GitHub issue #${Issue}: $title

$($meta.body)

Rules for this run:
- Stay strictly within the scope of the issue.
- Do not edit anything under docs/specs, docs/runbooks, or AGENTS.md.
- Verify your change with a command or test where possible and include the command you ran.
- Finish with a short summary: what changed, how it was verified, anything left for the reviewer.
"@
} else {
  $title = $Task
  $branch = "agent-local/" + (Get-Date -Format 'yyyyMMdd-HHmm')
  $prompt = @"
You are the LOCAL agent for this repository (model: $modelLabel). Read AGENTS.md first and follow it, especially the "Local agent" rules.

Task: $Task

Rules for this run:
- Do not edit anything under docs/specs, docs/runbooks, or AGENTS.md.
- Verify your change with a command or test where possible and include the command you ran.
- Finish with a short summary: what changed, how it was verified, anything left for the reviewer.
"@
}

git checkout -q -b $branch
$stamp = $branch -replace '[\\/]', '_'
$log = Join-Path $env:TEMP "agent-local-$stamp.log"
$promptFile = Join-Path $env:TEMP "agent-local-$stamp.prompt.txt"
$outFile = Join-Path $env:TEMP "agent-local-$stamp.last.txt"
[IO.File]::WriteAllText($promptFile, $prompt, (New-Object Text.UTF8Encoding $false))
if (Test-Path $outFile) { Remove-Item $outFile -Force }
Write-Host "Running codex exec (profile $Profile) on branch $branch ... log: $log"

# `codex exec -` reads the prompt from stdin; -o writes the final message to a file.
# Run through cmd.exe so stdin/stderr redirection happens outside PowerShell: in PowerShell 5.1,
# redirecting a native command's stderr turns every progress line into an ErrorRecord.
$prevEap = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
& cmd.exe /c "codex exec --profile $Profile --sandbox workspace-write -C ""$repo"" -o ""$outFile"" - < ""$promptFile"" 2> ""$log"" 1>nul"
$codexExit = $LASTEXITCODE
$ErrorActionPreference = $prevEap

$summary = if (Test-Path $outFile) { (Get-Content $outFile -Raw).Trim() } else { '(no final message; see log)' }
Write-Host "---- agent summary ----"
Write-Host $summary
if ($codexExit -ne 0) { Write-Warning "codex exec exited with $codexExit (see $log)." }

git add -A
$changes = git status --porcelain
if (-not $changes) {
  Write-Host "No changes produced. Returning to main and deleting $branch."
  git checkout -q main
  git branch -q -D $branch
  exit $codexExit
}

$ref = if ($Issue) { " (#$Issue)" } else { '' }
$msg = @"
agent(local): $title$ref

Generated by the local agent ($modelLabel via Codex CLI, profile $Profile).
Needs review by a different agent before merge.

$summary
"@
$msg | git commit -q -F -

if ($NoPR) {
  Write-Host "Committed on $branch (no PR requested)."
  exit 0
}

git push -q -u origin $branch
$prBody = @"
Automated PR from the local agent ($modelLabel, Codex profile ``$Profile``).
$(if ($Issue) { "Closes #$Issue" })

## Agent summary
$summary

## Review checklist
- [ ] Scope matches the issue
- [ ] No changes under docs/specs, docs/runbooks or AGENTS.md
- [ ] Verification command in the summary actually passes
"@
gh pr create --title "agent(local): $title$ref" --body $prBody --label "agent:local" --label "needs-review" --base main --head $branch
git checkout -q main
